#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Usage: addext [ext] <name>"
    exit 1
fi

ext="$1"

shift

for file in $@; do
    if [ -f "$file" ] && [[ "$file" != *"$ext" ]]; then
        echo "renaming $file to $file$ext"
        mv "$file" "$file$ext"
    fi
done

